name: Run flutter gen-l10n

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.8'

    - name: Install dependencies
      run: flutter pub get

    - name: Generate localization files
      run: flutter gen-l10n
