name: Update ARB Files

on:
  pull_request:
    branches:
      - main

jobs:
  update-arb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8' 

      - name: Replace "ur-PK" with "ur" in app_ur.arb
        run: |
          sed -i 's/"ur-PK"/"ur"/g' lib/l10n/app_ur.arb

      - name: Replace "es-ES" with "es" in app_es.arb
        run: |
          sed -i 's/"es-ES"/"es"/g' lib/l10n/app_es.arb

      - name: Run flutter gen-l10n
        run: flutter gen-l10n

      - name: Run flutter pub run crowdin_sdk:gen
        run: flutter pub run crowdin_sdk:gen

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated ARB file updates and l10n generation"
          git push origin HEAD:${{ github.head_ref }}
        continue-on-error: true
